/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_winty_sec_Native */

#ifndef _Included_io_winty_sec_Native
#define _Included_io_winty_sec_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_winty_sec_Native
 * Method:    callRust
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_winty_sec_Native_callRust
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
